name: Deploy site to GitHub Pages
   
on:
  repository_dispatch:
    types: [trigger-site-workflow]

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'banerjeeakash97/mkdocs_website'
          token: ${{ secrets.token }}
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install yamllint
        run: pip install yamllint
      - name: Check MkDocs YAML configuration
        run: yamllint ./mkdocs.yml
        continue-on-error: true
      - name: Check Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: '**/*.md'
        continue-on-error: true
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-glightbox mkdocs-material-extensions pymdown-extensions
      - name: Build site (_site directory name is used for Jekyll compatiblity)
        run: mkdocs build --config-file ./mkdocs.yml --no-strict --site-dir ./_site
        env:
          CI: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
          
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
